### ISSUE TITLE
Weveral typos in the README.

### ISSUE THREAD

**Issue by rewolff** [wendlers/stm32-pwm-servo-sample#1]
There are several typos in the readme, exactly in keywords. 

Here is  a fix. 

diff --git a/README b/README
index 944fa74..c6cb2a0 100644
--- a/README
+++ b/README
@@ -1,5 +1,5 @@
-This is the exmaple firmware for my article posted on http://gpio.kaltpost.de/?page_id=412.
+This is the example firmware for my article posted on http://gpio.kaltpost.de/?page_id=412.

-The tutorial describes how to drive two servos (e.g. for a pan-tilt unit) through a PWM signal on an ARM Conrtex-M3.
+The tutorial describes how to drive two servos (e.g. for a pan-tilt unit) through a PWM signal on an ARM Cortex-M3.

-To build the exmaple you need an arm cross compiler and libopencm3 installed.
+To build the example you need an arm cross compiler and libopencm3 installed.

**Comment by wendlers** [comment]
Thanks for the patch. Applied that one.
